"""Megapitch class

Revision ID: 3225e700fbf1
Revises: 5a9e40abb78b
Create Date: 2022-05-12 02:49:13.710888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3225e700fbf1'
down_revision = '5a9e40abb78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('megapitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('pitch', sa.String(length=255), nullable=True),
    sa.Column('contributors', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('megapitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'megapitch', ['megapitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'megapitch_id')
    op.drop_table('megapitch')
    # ### end Alembic commands ###
