"""email and passkey

Revision ID: 5216178a0091
Revises: ccd0f6566acb
Create Date: 2022-05-11 00:47:34.490980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5216178a0091'
down_revision = 'ccd0f6566acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
